apiVersion: apps/v1
kind: Deployment
metadata:
  name: todoapp-deployment
  labels:
    app: todoapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todoapp
  template:
    metadata:
      labels:
        app: todoapp
    spec:
      containers:
      - name: project2
        image: project2:another
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: todoapp-service
spec:
  selector:
    app: todoapp
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 3000